# Generated by Django 5.0.7 on 2026-07-14 03:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('rutas', '0002_alter_ruta_options_ruta_nombre_and_more'),
        ('servicios', '0008_servicio_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteraEmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emisor', models.CharField(blank=True, max_length=160)),
                ('nit_emisor', models.CharField(blank=True, max_length=40)),
                ('direccion_emisor', models.CharField(blank=True, max_length=220)),
                ('telefono_emisor', models.CharField(blank=True, max_length=80)),
                ('email_emisor', models.EmailField(blank=True, max_length=254)),
                ('logo_static_path', models.CharField(default='icons/Logo.png', max_length=180)),
                ('prefijo_cuenta_cobro', models.CharField(default='CC', max_length=12)),
                ('proximo_consecutivo', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notas_estado_cuenta', models.TextField(blank=True)),
                ('notas_cuenta_cobro', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cartera_config', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'configuracion de cartera',
                'verbose_name_plural': 'configuraciones de cartera',
            },
        ),
        migrations.CreateModel(
            name='CuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.PositiveIntegerField()),
                ('numero', models.CharField(max_length=32)),
                ('emitida_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cobro', to='empresa.cliente')),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_cobro_emitidas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cobro', to='empresa.empresa')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_cobro', to='servicios.servicio')),
            ],
            options={
                'ordering': ['-emitida_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PagoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata'), ('TARJETA', 'Tarjeta'), ('ANTICIPO', 'Anticipo legacy'), ('AJUSTE', 'Ajuste autorizado'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('impacta_caja', models.BooleanField(default=False)),
                ('anulado', models.BooleanField(default=False)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=240)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cartera_anulados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_cartera', to='empresa.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_cartera', to='empresa.empresa')),
                ('movimiento_caja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago_servicio', to='rutas.movimientocaja')),
                ('movimiento_reversion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago_servicio_revertido', to='rutas.movimientocaja')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cartera_registrados', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_cartera', to='rutas.ruta')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='servicios.servicio')),
            ],
            options={
                'ordering': ['-fecha_pago', '-creado_en', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuentacobro',
            constraint=models.UniqueConstraint(fields=('empresa', 'consecutivo'), name='cuenta_cobro_consecutivo_empresa'),
        ),
        migrations.AddConstraint(
            model_name='cuentacobro',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='cuenta_cobro_numero_empresa'),
        ),
        migrations.AddIndex(
            model_name='pagoservicio',
            index=models.Index(fields=['empresa', 'fecha_pago'], name='cartera_pag_empresa_d1998d_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoservicio',
            index=models.Index(fields=['servicio', 'anulado'], name='cartera_pag_servici_c2e931_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoservicio',
            index=models.Index(fields=['cliente', 'fecha_pago'], name='cartera_pag_cliente_f503e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagoservicio',
            constraint=models.CheckConstraint(check=models.Q(('valor__gt', 0)), name='pago_servicio_valor_positivo'),
        ),
    ]
