# Generated by Django 5.0.7 on 2025-10-07 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('estado_pago', models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=10)),
                ('dir_recogida', models.CharField(max_length=200)),
                ('lat_recogida', models.FloatField(blank=True, null=True)),
                ('lon_recogida', models.FloatField(blank=True, null=True)),
                ('recogido_en', models.DateTimeField(blank=True, null=True)),
                ('dir_entrega', models.CharField(max_length=200)),
                ('lat_entrega', models.FloatField(blank=True, null=True)),
                ('lon_entrega', models.FloatField(blank=True, null=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('valor_recibido', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.cliente')),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.empresa')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='rutas.ruta')),
            ],
        ),
    ]
