# Generated by Django 5.0.7 on 2025-10-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='observaciones',
            new_name='notas',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='dir_entrega',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='dir_recogida',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='ejecutado_por',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='entregado_en',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='lat_entrega',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='lat_recogida',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='lon_entrega',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='lon_recogida',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='recogido_en',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='valor_recibido',
        ),
        migrations.AddField(
            model_name='servicio',
            name='anticipo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='destino',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicio',
            name='origen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado_pago',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('ANT', 'Recibir anticipo'), ('PAG', 'Pagado')], default='PEND', max_length=4),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valor',
            field=models.PositiveIntegerField(),
        ),
    ]
