# Generated by Django 5.0.7 on 2025-10-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicio_entregado_servicio_recogido'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='entregado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='lat_entrega',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='lat_recogida',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='lon_entrega',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='lon_recogida',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='recogido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
