# Generated by Django 5.0.7 on 2025-10-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_rename_observaciones_servicio_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicio',
            name='recogido',
            field=models.BooleanField(default=False),
        ),
    ]
