# Generated by Django 5.0.7 on 2025-10-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_servicio_options_serviciocomentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['ruta', 'orden', 'id']},
        ),
        migrations.AddField(
            model_name='servicio',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
