# Generated by Django 5.0.7 on 2025-10-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_servicio_options_servicio_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='valor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
