# Generated by Django 5.0.7 on 2025-10-15 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_alter_servicio_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Número de unidades asociadas al servicio (mínimo 1).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
