# Generated by Django 5.0.7 on 2026-07-14 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_servicio_cantidad'),
        ('cartera', '0002_migrar_anticipos_a_pagos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='anticipo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='estado_pago',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Numero de unidades asociadas al servicio (minimo 1).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
