# Generated by Django 5.0.7 on 2025-10-07 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={},
        ),
        migrations.AddField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(blank=True, help_text='Ej: Jardin - Medellin - Jardin', max_length=150),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='base_efectivo',
            field=models.DecimalField(decimal_places=2, default=200000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=20),
        ),
    ]
